obj-m := kvm.o kvm-intel.o kvm-amd.o
kvm-objs := kvm_main.o x86.o mmu.o emulate.o irq.o i8259.o pmu.o \
	 lapic.o ioapic.o preempt.o i8254.o coalesced_mmio.o irq_comm.o \
	 eventfd.o compat-x86.o async_pf.o cpuid.o irqchip.o \
	 ../external-module-compat.o
ifeq ($(CONFIG_IOMMU_API)$(CONFIG_PCI),yy)
kvm-objs += assigned-dev.o iommu.o
endif
kvm-intel-objs := vmx.o
kvm-amd-objs := svm.o

kvm-objs += ../srcu.o

CFLAGS_kvm_main.o = -DKVM_MAIN
